### ISSUE TITLE
🐣 [FEATURE] 채팅방 최신목록 정렬

### ISSUE THREAD

**Issue by jypark92** [Doong-Ji/nestalk-backend-spring#15]
## 📄 이슈 내용
- 채팅방 최신목록 정렬

## 📝 상세 내용
- 채팅방 최신목록으로 정렬 기능 구현

## ✔ 체크리스트
- [ ] 채팅방 목록 최신 순으로 정렬 기능 구현이 되었는가?
- [ ] TEST CODE 작성이 되었는가?

**Comment by hyojin107** [comment]
채팅방 목록 조회와 합쳐질 예정이므로, 해당 이슈를 종료합니다.
